### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by hylipiessa** [nicksinger/adp_downloader#8]
```
python3.11 downloader.py 
Welcome! Starting up the adpworld.de scraper.
Trying to log in… Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hylipiessa/Documents/ADP/adp_downloader_old/downloader.py", line 126, in <module>
    if adpworld.login():
       ^^^^^^^^^^^^^^^^                                                                                                                                                                       
  File "/home/hylipiessa/Documents/ADP/adp_downloader_old/adp.py", line 139, in login                                                                                                         
    sign_in_identify_data = req.json()                                                                                                                                                        
                            ^^^^^^^^^^                                                                                                                                                        
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 978, in json                                                                                                              
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)                                                                                                                                        
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  
```

**Comment by nicksinger** [comment]
Currently the login flow is broken. I will try to fix it but cannot promise you any time estimate. IIRC I think it was not a simple fix.

**Comment by hylipiessa** [comment]
Additional information :
python311-beautifulsoup4-4.12.3-1.3.noarch
python311-requests-2.32.3-2.1.noarch

**Comment by nicksinger** [comment]
I wanted to look into the problem but my account seems blocked somehow. I currently try to recover it but I need external help for that. If somebody wants to fix it themself; I'm happy to review PRs!

**Comment by hylipiessa** [comment]
If you have already in process of getting the account access being fixed ... I can wait .
Python code is not my speciality .

**Comment by roseswe** [comment]
Still broken. 
$ python --version
Python 3.10.12
(ZorinOS 17.2)

**Comment by nicksinger** [comment]
Unfortunately I never got the password based login to work again. They just do too much javascript obfuscation. I however just implemented cookie-based login which at least allows you to download all your documents once. The cookie expires quite fast so a periodic cron job fetching your documents will break fast. Take a look at the updated README.md how to use it.

**Comment by ricardobranco777** [comment]
It's working for me!
